name: Deploy WebApp

on:     
    workflow_run:
        workflows: ["Build and Push Docker Image"]
        types:
        - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
    #   - name: Azure CLI Login
    #     uses: azure/login@v2
    #     with:
    #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #       audience: api://AzureADTokenExchange
      - run: echo ${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'proa-webapp'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/weizhe-sha/proa-interview:main'