name: Infra

on:     
    workflow_run:
      workflows: ["Docker"]
      types:
        - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
        TERRAFORM_DIR: "./infra"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          audience: api://AzureADTokenExchange

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=$TERRAFORM_DIR init

      - name: Terraform Plan
        run: |
            terraform -chdir=$TERRAFORM_DIR plan \
                -var="github_username=${{ github.actor }}" \
                -var="github_PAT=${{ secrets.IMAGE_PULL_TOKEN }}" \
                -var="github_repo=${{ github.repository }}"\
                -var="repo_branch=main"\
                -out main.tfplan

      - name: Terraform Apply
        run: |
            terraform -chdir=$TERRAFORM_DIR apply \
                -var="github_username=${{ github.actor }}" \
                -var="github_PAT=${{ secrets.IMAGE_PULL_TOKEN }}" \
                -var="github_repo=${{ github.repository }}"\
                -var="repo_branch=main"\
                -auto-approve main.tfplan