name: Deploy to Azure

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  deploy:
    if: contains(github.event.head_commit.message, 'azure')
    runs-on: ubuntu-latest
    env:
        TERRAFORM_DIR: "./infra"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=$TERRAFORM_DIR init

      - name: Terraform Plan
        run: terraform -chdir=$TERRAFORM_DIR plan\
            -var="github_username=${{ github.actor }}" -var="github_PAT=${{ secrets.GITHUB_TOKEN }}"\
            -out main.tfplan

      - name: Terraform Apply
        run: terraform -chdir=$TERRAFORM_DIR apply\
            -var="github_username=${{ github.actor }}" -var="github_PAT=${{ secrets.GITHUB_TOKEN }}"\
            -auto-approve main.tfplan

    #   - name: Azure Login
    #     uses: azure/login@v2
    #     with:
    #       creds: ${{ secrets.AZURE_CREDENTIALS }}
