name: Infra

on: issue_comment

jobs:
  deploy:
    if: contains(github.event.head_commit.message, 'infra')
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    env:
        TERRAFORM_DIR: "./infra"
        BRANCH: "main"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            audience: api://AzureADTokenExchange

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
            terraform -chdir=$TERRAFORM_DIR init \
                -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
                -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}"

      - name: Terraform Plan
        run: |
            terraform -chdir=$TERRAFORM_DIR plan \
                -out main.tfplan

      - name: Terraform Apply
        run: |
            terraform -chdir=$TERRAFORM_DIR apply \
                -auto-approve main.tfplan